### ISSUE TITLE
Install documentation

### ISSUE THREAD

**Issue by henricook** [mattlogan/SurgePriceWidget#1]
This looks super useful, I'd love it! Will it work in other countries such as the UK where we only have uberx, exec and XL? Or is it hard coded to American car types?

Would it be possible to have more detailed install information or pre-built apks?

**Comment by mattlogan** [comment]
Hey there,

I think it should work in other countries but I can't say for sure.

I can't do pre-built APKs since that would mean giving everyone access to my (unpaid) API key. Uber restricts API usage unless you pay them, I think.

This might be pretty tricky if you're not familiar with Android development tools. In a nutshell, you need to:

a) Clone the project repo
b) Install Android Studio
c) Open the project in Android Studio
d) Go to developer.uber.com and get an API key, then follow the instructions in the readme to add the API key to your project
e) Build and run

With all that said, I haven't touched this project in three years so I can't guarantee it'll still work. Thanks for your interest!

**Comment by henricook** [comment]
Dev tools totally cool, thanks! I'll let you know how it turns out!

**Comment by henricook** [comment]
Do you have a better surge tracking solution now @mattlogan  out of interest? All the apps i have are a bit clunky and rubbish which is why i'm exploring this

**Comment by mattlogan** [comment]
Sorry I don't! Seems like a good idea for a more full-featured app though.
